title: Portefølje

author: Eva Pedersen

navbar-links:
  Hjem: "index"
  Om Mig: "aboutme"
  Læringsmål:
    - Generelle Læringsmål: "generelobjectives"
    - Projektkoordinering: "project-coordination"
    - NIS2-direktivet: "nis2"
  Læringsplan: "learningplan"
  Blog:
    - Uge 36: "week36"
    - Uge 37: "week37"
    - Uge 38: "week38"
    - Uge 39: "week39"
    - Uge 40: "week40"
    - Uge 41: "week41"
    - Uge 43: "week43"
    - Uge 44: "week44"
    - Uge 45: "week45"
    - Uge 46: "week46"
    - Uge 47: "week47"
    - Uge 48: "week48"
  Litteraturliste: "resources"
  Dokumentation:
    - Projektkoordinering: "dprojectcoordination"
    - NIS2: "dnis2"

social-network-links:
  email: "empe54079@edu.ucl.dk"
  github: "Evaped"
  linkedin: eva-pedersen-12529b216

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb

# Build settings
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
